const express=require('express')
const login = require('../Controller/Login')
const sinup = require('../Controller/Sinup')
const Productuser = require('../Controller/createproduct')
const Getproducts = require('../Controller/getproduct')
const getall = require('../Controller/Getallproducts')
const updateproduct = require('../Controller/editproduct')
const deleteprod = require('../Controller/deleteproduct')
const Cartproducts = require('../Controller/cart')
const Cartadd = require('../Controller/Createcart')
const getallcart = require('../Controller/Getallcart')
const deletecart = require('../Controller/deletecart')
const clientlogin = require('../Controller/clientlogin')
const clientsinup = require('../Controller/clientsinup')

const router=express.Router()
router.route('/login').post(login)
router.route('/sinup').post(sinup)
router.route('/clientsinup').post(clientsinup)
router.route('/clientlogin').post(clientlogin)
router.route('/addproduct').post(Productuser)
router.route('/addcart').post(Cartadd)
router.route('/viewproduct/:id').get(Getproducts)
router.route('/getallproduct').get(getall)
router.route('/getallcart').get(getallcart)
router.route('/editproduct/:id').put(updateproduct)
router.route('/deletprod/:id').delete(deleteprod)
router.route('/deletecart/:id').delete(deletecart)
router.route('/cart/:id').get(Cartproducts)

module.exports=router